### ISSUE TITLE
Run fails on Windows

### ISSUE THREAD

**Issue by CaptainParalytic** [priithaamer/adyen-skinbuilder#20]
I have installed this on Windows and when I try to run it I get:

C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such fil
e -- bundler/setup (LoadError)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/adyen-skinbuilder-0.4.3/lib/adyen-skinbuilder/serve
r.rb:2:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/adyen-skinbuilder-0.4.3/bin/adyen-skinbuilder:3:in
`<top (required)>'
        from C:/Ruby193/bin/adyen-skinbuilder:23:in `load'
        from C:/Ruby193/bin/adyen-skinbuilder:23:in`<main>'

Any ideas?

**Comment by rngtng** [comment]
do you have bundler installed?

`gem list | grep bundler`

Sorry don't have a windows machine here to test... :(

**Comment by CaptainParalytic** [comment]
No I don't have bundler. Is it a pre-req?

**Comment by CaptainParalytic** [comment]
I installed bundler and now am getting:

C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such fil
e -- win32/process (LoadError)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/vegas-0.1.11/lib/vegas/runner.rb:8:in `<top (requir
ed)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/adyen-skinbuilder-0.4.3/bin/adyen-skinbuilder:31:in
`<top (required)>'
        from C:/Ruby193/bin/adyen-skinbuilder:23:in `load'
        from C:/Ruby193/bin/adyen-skinbuilder:23:in`<main>'

**Comment by Akashrine** [comment]
Any news on this error ? I've got the same here.

**Comment by rngtng** [comment]
sorry no, still havn't found time and a win machine to reproduce and fix. The given error doesn't help me much. Do you see the same message?

**Comment by Amaranthos** [comment]
Looks like the solution is to run 

`gem install win32-process windows-pr`

as per https://github.com/test-kitchen/test-kitchen/issues/385
